### PR TITLE
Remove duplicate files instead of throwing an exception.

### PR DESCRIPTION
**Pull request by thorgeir**
When the _PackageContent variable contains duplicates I think it should not result in an exception, maybe a warning but not an exception. Because form my experience the duplicates are not different files but the same file referenced twice.
Removing duplicates in the CreatePackage task works and the package contains all the files it should.

Maybe the duplicates could be resolved earlier in the AssignPackagePath task?

### CODE REVIEW

**Comment by kzu** [comment]
> Because form my experience the duplicates are not different files but the same file referenced twice.

Maybe we can make sure of that by also comparing the actual files? (maybe a quick size+update time?)

Because picking multiple different source files and attempting to package them to the same location is most definitely an authoring error that you'd want to flag and make very obvious, I think.

Would need adjusting the unit test that verifies this behavior:
```
src\Build\NuGet.Build.Packaging.Tests\given_a_library_with_private_assets_reference.cs(60,0): at NuGet.Build.Packaging.given_a_library_with_private_assets_reference.when_getting_package_contents_then_contains_private_lib_assets_as_primary_output_and_also_package_reference()
      NuGet.Build.Packaging.given_duplicate_package_files.build_fails [FAIL]
        Assert.Equal() Failure
        Expected: Failure
        Actual:   Success
        Stack Trace:
          src\Build\NuGet.Build.Packaging.Tests\given_duplicate_package_files.cs(20,0): at 
```
(current CI failure)

**Comment by thorgeir** [comment]
Sure, I'll try to add that.
Regarding the unit tests, I was unable to compile the multi_platform_solution locally. I have xamarin installed but the ios and android projects are not loading, what am I missing?

**Comment by kzu** [comment]
You need to install the .NET Core SDK which brings in the SDK-style projects/imports.

The updated implementation looks 👍

**Comment by thorgeir** [comment]
I can't see how this change affected the `given_a_library_with_private_assets_reference.when_getting_package_contents_then_contains_private_lib_assets_as_primary_output_and_also_package_reference` test I tried reverting back to the original code and it still failed.

**Comment by kzu** [comment]
hm, that's weird, since there were no other code changes between the last successful build and this one :(

**Pull request merged**
