### PR TITLE
Do not include "contentFiles/" prefix in <contentFiles/> (issue #6556)

### PR DESCRIPTION
**Pull request by azeno**
Nuget expects the include paths relative to the package contentFiles folder (see official examples https://docs.microsoft.com/en-us/nuget/reference/nuspec#including-content-files). Otherwise the BuildAction, CopyToOutput and Flatten attributes have no effect. This PR fixes that by adjusting the included path accordingly.

### CODE REVIEW

**Comment by azeno** [comment]
Was also already reported here: https://github.com/NuGet/Home/issues/6556

**Comment by kzu** [comment]
See https://github.com/NuGet/Home/issues/6556#issuecomment-418474529. I don't think this PR is correct.

**Review by jpsalada — APPROVED** [review]

**Comment by jpsalada** [comment]
Can someone approve these changes?  We really need this.

**Comment by kzu** [comment]
Read my comment above and on the linked issue plz.

Thanks

**Comment by jpsalada** [comment]
Read the answers to your comment please.

**Comment by jpsalada** [comment]
@kzu 

I have created a TestProject example. If I put my content dependency this way:
```
  <ItemGroup>
    <Content Include="mybinarydependency.bin" copyToOutput="true"buildAction="content"flatten="true" packagePath="contentFiles\any\any\mybinarydependency.bin">
    </Content>
  </ItemGroup>
```

Everything in the package goes ok, but nuspec file get _contentFiles_ in the directory specification:
```
 <contentFiles>
      <files include="contentFiles\any\any\mybinarydependency.bin" buildAction="content" copyToOutput="true" flatten="true" />
    </contentFiles>
```

The problem is the nuget restore will not be able to detect the file and will assume default configuration for the dependency (compile, not copy to output), making it impossible to have this type of content in the nuget. Content from _project.assets.json_:
```

        "contentFiles": {
          "contentFiles/any/any/mybinarydependency.bin": {
            "buildAction": "**Compile**",
            "codeLanguage": "any",
            "copyToOutput": **false**
          }
```

Now if I directly change nuget package, namely the nuspec setting _include_ to "any\any\mybinarydependency.bin", while maintaining the directory structure "contentFiles\any\any\mybinarydependency.bin" within the package, nuget restore will detect the file and it will assume the correct properties that have been configurated in the .csproj. **buildAction** to content and **copyToOutput** to true.:

```
        "contentFiles": {
          "contentFiles/any/any/mybinarydependency.bin": {
            "buildAction": "**Content**",
            "codeLanguage": "any",
            "copyToOutput": **true**,
            "outputPath": "mybinarydependency.bin"
          }
```

**Review by kzu — APPROVED** [review]

**Comment by jpsalada** [comment]
Thank you so much!

**Pull request merged**
